### ISSUE TITLE
Default values for `Ft` and `Fn` if `UV` and `N` are provided

### ISSUE THREAD

**Issue by abhimadan** [sgsellan/gpytoolbox#102]
The `write_mesh` function can optionally take in texture coordinates `UV` and normals `N`, which require corresponding index matrices `Ft` and `Fn`, respectively. However, the function doesn't seem to check for cases where, for example, `UV` is provided but `Ft` is not provided. This results in situations where a written .obj file can contain `vt` rows but the `f` rows only contain vertex indices and no texture indices, so the file does not actually have a valid UV map.

I think a reasonable default in these cases would be to fall back on `F`, if there are as many texture coordinates/normals as vertices and `Ft`/`Fn` are not provided. If this isn't satisfied, I think the function should return an error. If it's preferable to avoid defaults and make the API explicit, I still think the function should return an error when `UV`/`N` is provided but `Ft`/`Fn` is not, so the semantics are clear.

**Comment by odedstein** [comment]
I think this is a reasonable suggestion. Thanks, Abhishek.
Do you want to make a PR for it?

**Comment by abhimadan** [comment]
Yeah, I can make a PR. Thanks!
