### ISSUE TITLE
Resolution parameters switched in documentation for torus function

### ISSUE THREAD

**Issue by zoemarschner** [sgsellan/gpytoolbox#113]
The [documentation](https://gpytoolbox.org/0.1.0/torus/) for the `torus` function states that the first parameter (`nR`) is the number of vertices along the large perimeter and the second parameter (`nr`) is the number of vertices along the small perimeter, but in the code the meaning of these parameters are switched. 

`V,F = gpy.torus(10, 3, R=1., r=0.1)` produces:
![torcus_actual](https://github.com/sgsellan/gpytoolbox/assets/20357945/3e6fbdba-ece2-4843-866f-ae1c94dd7139)

But according to the documentation should produce:
![torus_expected](https://github.com/sgsellan/gpytoolbox/assets/20357945/fcbb8ab0-eb63-4ee1-9dcb-943b12f179e9)

**Comment by odedstein** [comment]
Thanks for pointing this out, Zoë!

**Comment by odedstein** [comment]
This was fixed by #114.
