### ISSUE TITLE
Does Gpytoolbox provide a visual function?

### ISSUE THREAD

**Issue by XYZ-Lenari** [sgsellan/gpytoolbox#128]
Excuse me，Does Gpytoolbox have a visual function, for example, I want to display the swept body calculated by the swept_volume function, how can I do it?

**Comment by sgsellan** [comment]
Hi! We do not have visualization tools in the toolbox; we encourage you to try [polyscope](https://polyscope.run/py/). For example, to use it with gpytoolbox:

```python
from gpytoolbox import read_mesh
import polyscope as ps

v, f = read_mesh("some/path/to/mesh.obj")
ps.init()
ps.register_surface_mesh("my mesh", v, f)
ps.show()
```

**Comment by sgsellan** [comment]
Closing this issue, do feel free to re-open if you need more help!

**Comment by kamiradi** [comment]
Hi,
In your `stochastic_poisson_surface` example, to visualise in 3D you had provided a script. In it you mention the following transformations. May I ask what these transformations do? I know these could be very simple, but just so that I can use it in a more repeatable manner.

```
tet_verts = 2.2*tet_verts - 1.1
R = np.array([[0.0,0.0,1.0],[0.0,1.0,0.0],[-1.0,0.0,0.0]]) @ np.array([[1.0,0.0,0.0],[0.0,0.0,1.0],[0.0,-1.0,0.0]])
tet_verts = tet_verts @ R
tet_verts[:,0] = - tet_verts[:,0]
tet_verts[:,1] = - tet_verts[:,1]
ps.init()
```

**Comment by sgsellan** [comment]
Hi! This code scales, centers and rotates a shape along two axes.

**Comment by kamiradi** [comment]
@sgsellan What is the need for these operations, is it because of LHS, RHS representations within the read_mesh function and polyscope display?

**Comment by kamiradi** [comment]
@sgsellan Thank you for your prompt reply. I thought I may have missed something there and decided to ask.

**Comment by sgsellan** [comment]
No worries! Let me know if I can help with anything else :)
