### ISSUE TITLE
"ImportError: Gpytoolbox cannot import its C++ binding" when using gpytoolbox.copyleft.lazy_cage on Windows

### ISSUE THREAD

**Issue by zhuzihan728** [sgsellan/gpytoolbox#72]
The error occurs at the line

```
     46 try:
---> 47     from gpytoolbox_bindings_copyleft import _mesh_union_cpp_impl
     48     from gpytoolbox_bindings_copyleft import _mesh_intersection_cpp_impl

ImportError: DLL load failed while importing gpytoolbox_bindings_copyleft: The specified module could not be found.

During handling of the above exception, another exception occurred:
```

Any idea how to fix this?

**Comment by sgsellan** [comment]
Thanks for reporting this issue! Can you confirm which version of gpytoolbox you are using and how you installed it? (e.g., did you use `pip install gpytoolbox`?) If you could also provide us with a minimal working example code that we can run to replicate your problem, that will be very useful

**Comment by zhuzihan728** [comment]
gpytoolbox 0.1.0 installed by `pip install gpytoolbox`
To reproduce 
```
from gpytoolbox.copyleft import lazy_cage
vv, ff = lazy_cage(v, f) # for some vertices and faces

```

**Comment by zhuzihan728** [comment]
> gpytoolbox 0.1.0 installed by `pip install gpytoolbox` To reproduce
> 
> ```
> from gpytoolbox.copyleft import lazy_cage
> vv, ff = lazy_cage(v, f) # for some vertices and faces
> ```

System win11

**Comment by sgsellan** [comment]
Sorry for the delay! If you install a previous version of gpytoolbox, e.g., with `pip install gpytoolbox==0.0.1` or `pip install gpytoolbox==0.0.2`, do you get the same error?

Silvia
