### ISSUE TITLE
pip install gpytoolbox==0.1.0     gpytoolbox_bindings_copyleft

### ISSUE THREAD

**Issue by AAA-Fei** [sgsellan/gpytoolbox#82]
hello @sgsellan 
I execute pip install gpytoolbox==0.1.0
I checked the previous version and the latest version seems to be missing something

The following problems occurred：
from gpytoolbox_bindings_copyleft import _swept_volume_impl
ImportError: DLL load failed while importing gpytoolbox_bindings_copyleft: 找不到指定的模块。

thank you!

**Comment by sgsellan** [comment]
Hi @AAA-Fei . Could you let us know if this happens with our latest release? `pip install gpytoolbox=0.2.0` 

I believe this problem is fixed, but I'd love your confirmation. If we don't hear back from you we will remove this issue as stale.
