### ISSUE TITLE
PLY file not read correctly

### ISSUE THREAD

**Issue by odedstein** [sgsellan/gpytoolbox#97]
This issue was discovered by Jack Zhang.

Our PLY reader fails to read in the face list for a triangle mesh. libigl reads the ply just fine. If I open the triangle mesh in blender and reexport as PLY, it works though.
Simple example (the mesh files are in [meshes.zip](https://github.com/sgsellan/gpytoolbox/files/13161269/meshes.zip)):
```python
import gpytoolbox as gpy
import igl

V_ply,F_ply = gpy.read_mesh("mesh.ply")
print(f"V_ply: {V_ply.shape}, F_ply: {F_ply.shape}")

V_ply_igl,F_ply_igl = igl.read_triangle_mesh("mesh.ply")
print(f"V_ply_igl: {V_ply_igl.shape}, F_ply_igl: {F_ply_igl.shape}")

V_ply_blender,F_ply_blender = gpy.read_mesh("mesh_exported_by_blender.ply")
print(f"V_ply_blender: {V_ply_blender.shape}, F_ply_blender: {F_ply_blender.shape}")

V_obj,F_obj = gpy.read_mesh("mesh.obj")
print(f"V_obj: {V_obj.shape}, F_obj: {F_obj.shape}")
```

This produces:

```
V_ply: (2802, 3), F_ply: (0, 0)
V_ply_igl: (2802, 3), F_ply_igl: (934, 3)
V_ply_blender: (2802, 3), F_ply_blender: (934, 3)
V_obj: (2802, 3), F_obj: (934, 3)
```
I.e., gpytoolbox returns an empty triangle list on the provided `mesh.ply`, but not on the reexported `mesh_exported_by_blender.ply`.

What could cause this?
Looking at the two PLY binary files in detail, one difference that I can see is that for `mesh.ply`, the vertex indices are given as int, and for `mesh_exported_by_blender.py` the vertex indices are given as uint:
```
header of mesh.ply:
element face 934.property list uchar int vertex_index

header of mesh_exported_by_blender.py:
element face 934.property list uchar uint vertex_indices
```

Indeed, our PLY binding just seems to assume vertex indices in the face list will always be uint. Libigl's does not, they have a switch statement supporting various types.

**Comment by sgsellan** [comment]
Haha! Thanks to both for catching this. After some more sleuthing, it seems like the difference is *not* in the uint vs int part; rather, in the "vertex_indices" vs "vertex_index" part at the end of that line 😛  Funny! Just made a [PR](https://github.com/sgsellan/gpytoolbox/pull/98) that fixes it, will merge it after checks.

P.S.: No word yet on whether it accepts "indeces"! ;-)
